language: java

# whitelist
branches:
  only:
    - master
    - develop

before_script:
  - echo $JAVA_OPTS
  - ps aux

before_install:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e 'create database bsis;'
  - pip install --user codecov

after_success:
  - codecov

script: mvn -Dsurefire.useFile=false clean install

sudo: false
